server:
  port: 8881
spring:
  application:
    name: config-client
  cloud:
    config:
#      uri: http://CONFIG-SERVER # /foo/development
      discovery:
        enabled: true
        serviceId: config-server
      lable: master
      profile: dev
#      profiles: development
      name: user, config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/