spring:
  application: eureka-server

server:
  port: 9000

eureka:
  instance:
    hostname: eureka-server

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

debug: false