spring:
  application: eureka-server

server:
  port: 9001

eureka:
  instance:
    hostname: eureka-server1

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:9001/eureka
      defaultZone: http://eureka-server2:9002/eureka/

debug: false
