server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
#  config:
#    name: configserver
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/spring-cloud-samples/config-repo
          uri: https://github.com/WCF900905/springcloud-cnf/
#          uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: repo
          label: master
          username: wuchengfeiss@126.com
          password: a64630147